### ISSUE TITLE
Volume cloning across storage classes

### ISSUE THREAD

**Issue by mattcary** [kubernetes-csi/docs#490]
I'd like to revisit the volume cloning & storage classes discussion (eg, #181).

GCP PD now supports volume cloning from [a zonal PD into a regional PD](https://cloud.google.com/compute/docs/disks/create-disk-from-source#create-regional-clone). However, implementing this in kubernetes is a problem because zonal PDs are a different storage class from regional PDs.

Instead of forbidding cross-storage class cloning, it could be up to the csi driver to decide if the classes are compatible. This (probably?) requires the source volume storage class to be added to the create volume CSI API (that is, add source volume parameters in addition to the existing parameters in the request, which implicitly are for the destination).

Or perhaps there are better solutions?

**Comment by msau42** [comment]
cc @xing-yang @j-griffith @jsafrane for thoughts. I think it makes sense for the driver to be able to decide if the 2 storageclasses could support cloning. We already put the burden on the driver to verify this for snapshots, so I'm not sure why cloning should be treated differently.

**Comment by j-griffith** [comment]
We discussed this type of case when we were implementing cloning.  I agree it's something that should be enabled, but at the time there were a couple of reasons we didn't move forward with it:
* somewhat in determinant behavior for a user; not clear that the two SCs are related and can clone to each other
* SC includes in some cases info like disk type and fs.  This created a problem even in the case where a device could handle the cloning because you can easily ask for *impossible* clone scenarios; or you could end up with something completely unexpected

I do think it would be useful to put this together, the problem we ran in to before was just figuring out how do you eliminate the problem with the behavior not being explicit and the issue of storage class compatability (even on a backend device that can do the clone).  You run into things like disk types, AZs etc that IMO it becomes a bit more complex.  To me it almost seems like it would be better in this case to modify the SC to serve all AZs and to specify which AZ via the PVC spec.  That way theyr'e all under the same SC and it eliminates the cloning problem, you just have to solve the spec change and extra AZ info (still not trivial but safer IMO).  Just my 2 cents.

**Comment by mattcary** [comment]
> can do the clone). You run into things like disk types, AZs etc that IMO it becomes a bit more complex. To me it almost seems like it would be better in this case to modify the SC to serve all AZs and to specify which AZ via the PVC spec. That way theyr'e all under the same SC and it eliminates the cloning problem, you just have to solve the spec change and extra AZ info (still not trivial but safer IMO). Just my 2 cents.

The problem here is that zonal and regional PDs are different types, it's not just different AZs.

**Comment by j-griffith** [comment]
> The problem here is that zonal and regional PDs are different types, it's not just different AZs.

Understood, just reflecting on reasons that came up in the past.  The user experience being the main thing.  I think it's a useful feature would just be great if there was a way to make it clear to the user why it fails when they try to clone between incompatible storage classes.  

Maybe require a label on the SCs to indicate they're part of a "group" or something?  Basically just some way to indicate that they're linked.  The seems like it would be descriptive and configurable.

**Comment by jsafrane** [comment]
I think we have the same issue with snapshots. A snapshot taken from PVC A  with SC A may or may not be restore-able using SC B. We don't provide any labels or guidelines what SC can be used to restore a snapshot. Did we see users complaining about that? Shall we do the same (= nothing) in cloning too?

**Comment by j-griffith** [comment]
> I think we have the same issue with snapshots. A snapshot taken from PVC A with SC A may or may not be restore-able using SC B. We don't provide any labels or guidelines what SC can be used to restore a snapshot. Did we see users complaining about that? Shall we do the same (= nothing) in cloning too?

Correct, I think that was the point @msau42 was making (status quo with snapshots).  My opinion is it would probably be "ok" but it seems like we could do better.  I'd be happy to help if that makes any difference.
