### ISSUE TITLE
Add PR check (travis?) to verify generated files

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/docs#79]
Updating docs is a two step process:

1. Update file in `book/*`
2. Run generation command to generate files in `docs/*`

To ensure that some one doesn't accidentally only update `book/*` or only modifies the generated files, we should add a new PR check (via travis maybe?) to verify that generated files do not differ from the generated files in the PR.

**Comment by pohly** [comment]
IMHO having the generated docs in the repo doesn't scale. Just look at the number of times that some submitters had to rebase their PR because of merge conflicts in the generated HTML. Each time we merge one PR, we have to wait for rebasing.

I think it would be better to aim for something like this:
- remove generated docs from repo
- create docs in PR Travis jobs, publish result for review somehow somewhere
- in the Travis master build, publish the resulting docs at https://kubernetes-csi.github.io/docs/

**Comment by pohly** [comment]
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd explains how we can push generated docs into the repo's `gh_pages` branch from Travis for the master branch.

Publishing generated docs for PRs is harder, as we need a per-PR web server and establish some kind of garbage collection scheme. I personally have experience with pushing to AWS from Travis, so we could use https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html. However, someone needs to pay for it.

It might be simpler to just let PR reviewers decide whether they check out the PR (hub is very useful for that) and then build locally. This is not that much worse than the current situation, because the generated HTML in a PR cannot be viewed in the Github web UI either, one has to check out.

**Comment by pohly** [comment]
On Slack @lpabon said that he would like to have the docs generated by Travis.

Let me see whether I can prototype something.

/assign

**Comment by pohly** [comment]
I have a solution in https://github.com/pohly/kubernetes-csi-docs/tree/travis-docs.

However, before that  can be merged someone with the necessary permissions must set up Travis CI for the kubernetes-csi/docs repo (I can't do that, Travis CI doesn't find it when I search for it), create, add and encrypt a custom SSH key. I can walk whoever has the necessary repo permissions through this, but https://gist.github.com/domenic/ec8b0fc8ab45f39403dd explains it pretty well already.

**Comment by saad-ali** [comment]
I like the idea of getting rid of requirement for devs to generate docs and instead have it automatically done as part of merge. @lpabon should be able to help with the travis permissions/setup.
